name: Check for updated dist files
on:
  pull_request:

jobs:
  check-if-dist-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dist:
              - 'dist/**'
      - uses: mshick/add-pr-comment@v1
        if: steps.changes.outputs.dist == 'true'
        with:
          message: |
            Hi ðŸ‘‹

            Thank you for this contribution!
            Due to security reasons, we only allow updating the `dist/**` files with our own workflows.
          repo-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          repo-token-user-login: pulumi-bot
